{{- $root := . }}
{{- range $serviceName, $serviceConfig := .Values }}
{{- if (kindOf $serviceConfig | eq "map") }}
{{- if (or (eq $serviceName "frontend") (eq $serviceName "gatewayService")) }}
{{- if $serviceConfig.ingress.enabled -}}
{{- $fullName := printf "%s-%s" $root.Release.Name (lower $serviceConfig.name) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ecommerce-app.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ lower $serviceConfig.name }}
  {{- with $serviceConfig.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $serviceConfig.ingress.host | quote }}
      http:
        paths:
          - path: {{ $serviceConfig.ingress.path }}
            pathType: {{ $serviceConfig.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $serviceConfig.service.port }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}